### ISSUE TITLE
Failed to parse package.json

### ISSUE THREAD

**Issue by Criccle** [mendix/generator-mendix#18] opened 2016-06-30 10:50 UTC
Yesterday grunt would work just fine. Today I wanted to start working on a new widget, but when I run yo mendix I receive the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'update' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose stack Error: Failed to parse json
4 verbose stack No value found for key url at 26:12
4 verbose stack     "url": &#34;http://github.com/Criccle/MyWidget&#34;
4 verbose stack            ^
4 verbose stack     at parseError (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:379:11)
4 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:68:23)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd D:\Mendix Widgets\GoogleCombo2
6 error Windows_NT 10.0.10586
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
8 error node v4.2.6
9 error npm  v2.14.12
10 error file D:\Mendix Widgets\GoogleCombo2\package.json
11 error code EJSONPARSE
12 error Failed to parse json
12 error No value found for key url at 26:12
12 error     "url": &#34;http://github.com/Criccle/MyWidget&#34;
12 error            ^
13 error File: D:\Mendix Widgets\GoogleCombo2\package.json
14 error Failed to parse package.json data.
14 error package.json must be actual JSON, not just JavaScript.
14 error
14 error This is not a bug in npm.
14 error Tell the package author to fix their package.json file. JSON.parse
15 verbose exit [ 1, true ]
```

Any idea what I might be doing wrong or what I should do differently?

**Comment by JelteMX** [comment] 2016-06-30 12:30
Duplicate of #16

**Closed by JelteMX** 2016-06-30 12:30 UTC
